/* evalExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file an evaluator evaluateExpressions is definined that can evaluate 
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 * 
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the evaluator is the token list constructed by the scanner (in scanner.c). 
 * For the evaluation of a token list the method of *recursive descent* is used. 
 * It relies on the use of three functions for the recognition and evaluation of
 * terms, factors and expressions, respectively. 
 * These three functions are defined with mutual recursion, corresponding with the 
 * structure of the BNF grammar.
 */

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include "scanner.h"
#include "recognizeExp.h"
#include "evalExp.h"

/* The function valueNumber is an extension of acceptNumber: the second parameter
 * is a pointer. After successful execution it refers to the numerical value 
 * of the token that is recognized as a number.
 */



    

